sudo: required
services:
  - docker

before install:
  - docker build -t mastercheap/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mastercheap/docker-react npm run test

deploy:
  provider: elaticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-339713193475"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"